---
- name: Install Docker in rhel
  gather_facts: no
  hosts: all
  become: yes
  user: root
  tasks:
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docker-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes
    - name: Add epel-release repo
      yum:
       name: epel-release
       state: present


    - name: Install Docker
      package:
        name: docker-ce
        state: latest
    - name: Install Docker Compose
      package:
        name: docker-compose
        state: latest


    - name: Install packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - bash-completion
        - vim

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user vagrant to docker group
      user:
        name: vagrant
        groups: docker
        append: yes



