---
- name: Install Docker in rhel
  gather_facts: no
  hosts: all
  become: yes
  user: root
  tasks:
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes
    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docker-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes
    - name: Add epel-release repo
      yum:
       name: epel-release
       state: present
    - name: Install packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - bash-completion
        - vim
        - iptables-services


    - name: Make sure firewalld is stoped and disabled
      service:
        name: firewalld
        state: stopped
        enabled: no
    - name: Start and enable iptables
      service:
        name: iptables
        state: started
        enabled: yes
    # Must remove the reject rule and add it last. We can't/dunno how to order rules
    - name: remove - Reject input with icmp-host-prohibited
      iptables:
        state: absent
        chain: INPUT
        reject_with: icmp-host-prohibited
    - name: Allow Docker Swarm
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 2377
        jump: ACCEPT
        comment: docker swarm
    # Reject with icmp-host-prohibited
    - name: Add - Reject input with icmp-host-prohibited
      iptables:
        state: present
        chain: INPUT
        reject_with: icmp-host-prohibited
    - name: Reject forward with icmp-host-prohibited
      iptables:
        chain: FORWARD
        reject_with: icmp-host-prohibited


    - name: Install Docker
      package:
        name: docker-ce
        state: latest
    - name: Install Docker Compose
      package:
        name: docker-compose
        state: latest


    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user vagrant to docker group
      user:
        name: vagrant
        groups: docker
        append: yes


