Vagrant.configure("2") do |config|

  config.vm.box = "generic/centos7"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", inline: "yum install -y ansible",
    run: "once"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "install-docker.yml"
  end

  config.vm.define "maurice_moss" do |app|
    config.vm.boot_timeout = 400
    app.vm.hostname = "docker1"
    app.vm.network "private_network", ip: "10.5.0.11"
  end

  config.vm.define "gilfoyle" do |app|
    config.vm.boot_timeout = 400
    app.vm.hostname = "docker1"
    app.vm.network "private_network", ip: "10.5.0.12"
  end




end
